apiVersion: v2
name: app
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "0.1.0"
dependencies:
  - name: base-app
    alias: backend
    repository: "@platform-charts"
    version: 2.x.x
    export-values:
      - parent: werf
        child: werf